# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1a4d7fa2d3035266f7d48d08c73e4c0ad8af6fef5b6ed52e3f60d2da5f1af54b6bee45614142763d6d5a6868c035c5ca745f179eddc9ea6a7c513e5d52fd6a1

test:
  secret_key_base: fb5f26718bf24322b2e1716b148f5869a3fd2b73b4cea4e839aba79190791796e581c390d52d0c50528a45acc61e086bd3a004dd45165cff21148a23e3d537ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
